/*
 * Copyright 2019 Arcus Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
apply from: file("${rootDir}/gradle/subproject.gradle")

dependencies {
   api project(":agent:arcus-system")
   api project(":agent:arcus-router")

   api project(':common:arcus-client')
   api project(':common:arcus-common')

   implementation libraries.commonsIO
   implementation libraries.commons_lang
   implementation libraries.guava

   implementation netty_handler
   implementation netty_codec_http
   implementation netty_codec
   implementation netty_transport
   implementation netty_buffer
   implementation netty_common
   implementation netty_tcnative
   implementation netty_epoll
   implementation name: 'netty-transport-native-epoll-4.0.41.Final-linux-armpoky21'

   runtimeOnly libraries.javassist

   testImplementation project(':agent:arcus-test-agent')
}

