/*
 * Copyright 2019 Arcus Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
apply plugin: "me.champeau.jmh"

dependencies {
	api project(':common:arcus-client')
	api project(":common:arcus-metrics")
	api project(':common:arcus-model')
	

	api libraries.commonsCodec
	api libraries.commons_lang
	api libraries.commons_math
	api libraries.guava
	api libraries.gson
	api libraries.guice
	implementation libraries.sunrise_sunset_calc
	implementation netty_common

	runtimeOnly libraries.commonsConfig
	runtimeOnly libraries.jacksonCore
	runtimeOnly libraries.jacksonDatabind
	runtimeOnly libraries.jacksonMapper
	
	jmh libraries.jacksonCore
	jmh libraries.jacksonDatabind
	jmh libraries.jacksonMapper
	jmh 'org.msgpack:jackson-dataformat-msgpack:0.8.11'
	jmh 'com.fasterxml.jackson.module:jackson-module-afterburner:2.18.6'
}

jmh {
   jmhVersion = '1.13'
   duplicateClassesStrategy = DuplicatesStrategy.WARN

   includes = ['PerfGsonSerDe']
}

