/*
 * Copyright 2019 Arcus Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.iris.capability.generator.ts;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.iris.capability.definition.AttributeDefinition;
import com.iris.capability.definition.CapabilityDefinition;
import com.iris.capability.definition.Definition;
import com.iris.capability.definition.EventDefinition;
import com.iris.capability.definition.MethodDefinition;
import com.iris.capability.definition.ObjectDefinition;
import com.iris.capability.definition.ServiceDefinition;

public class TypeScriptProcessor {

   private static final Logger logger = LoggerFactory.getLogger(TypeScriptProcessor.class);

   private final File outputDirectory;

   public TypeScriptProcessor(String outputDirectoryName) throws IOException {
      outputDirectory = new File(outputDirectoryName);
      if (outputDirectory.isFile()) {
         throw new IOException("Output directory already exists as file.");
      }
      if (!outputDirectory.exists()) {
         if (!outputDirectory.mkdirs()) {
            throw new IOException("Output directory could not be created.");
         }
      }
      if (!outputDirectory.isDirectory()) {
         throw new IOException("Could not find or create output directory [" + outputDirectoryName + "]");
      }
      if (!outputDirectory.canWrite()) {
         throw new IOException("Do not have write permissions for directory [" + outputDirectoryName + "]");
      }
   }

   public void create(List<Definition> definitions) throws IOException {
      List<ObjectDefinition> allDefs = new ArrayList<>();
      for (Definition def : definitions) {
         if (def instanceof CapabilityDefinition || def instanceof ServiceDefinition) {
            allDefs.add((ObjectDefinition) def);
         }
      }

      // Sort alphabetically by name (case-insensitive to match JS localeCompare behavior)
      allDefs.sort(Comparator.comparing(Definition::getName, String.CASE_INSENSITIVE_ORDER));

      // Build namespace map (sorted, first definition name per namespace wins)
      Map<String, String> nsMap = new TreeMap<>();
      nsMap.put("base", "Base");
      for (ObjectDefinition def : allDefs) {
         nsMap.putIfAbsent(def.getNamespace(), def.getName());
      }

      StringBuilder sb = new StringBuilder();

      // Header
      sb.append("// Auto-generated by arcus-captools TypeScriptGenerator \u2014 DO NOT EDIT\n");

      // Hand-coded Base block
      sb.append("\n");
      sb.append("export const Base = {\n");
      sb.append("  NAME: 'Base',\n");
      sb.append("  NAMESPACE: 'base',\n");
      sb.append("  ATTR_ADDRESS: 'base:address',\n");
      sb.append("  ATTR_CAPS: 'base:caps',\n");
      sb.append("  ATTR_ID: 'base:id',\n");
      sb.append("  ATTR_IMAGES: 'base:images',\n");
      sb.append("  ATTR_INSTANCES: 'base:instances',\n");
      sb.append("  ATTR_NAME: 'base:name',\n");
      sb.append("  ATTR_TAGS: 'base:tags',\n");
      sb.append("  ATTR_TYPE: 'base:type',\n");
      sb.append("  CMD_GETATTRIBUTES: 'base:GetAttributes',\n");
      sb.append("  CMD_SETATTRIBUTES: 'base:SetAttributes',\n");
      sb.append("  EVENT_ADDED: 'base:Added',\n");
      sb.append("  EVENT_VALUECHANGE: 'base:ValueChange',\n");
      sb.append("  EVENT_DELETED: 'base:Deleted',\n");
      sb.append("} as const;\n");

      // Definition blocks
      for (ObjectDefinition def : allDefs) {
         sb.append("\n");
         emitBlock(sb, def);
      }

      // NAMESPACE_MAP
      sb.append("\n");
      sb.append("/** Maps namespace prefix to capability/service export name(s). */\n");
      sb.append("export const NAMESPACE_MAP: Record<string, string> = {\n");
      for (Map.Entry<String, String> entry : nsMap.entrySet()) {
         sb.append("  '").append(entry.getKey()).append("': '").append(entry.getValue()).append("',\n");
      }
      sb.append("};\n\n");

      writeFile("capabilities.ts", sb.toString());
      logger.info("Generated capabilities.ts with {} definitions", allDefs.size());
   }

   private void emitBlock(StringBuilder sb, ObjectDefinition def) {
      String name = def.getName();
      String namespace = def.getNamespace();

      sb.append("export const ").append(name).append(" = {\n");
      sb.append("  NAME: '").append(name).append("',\n");
      sb.append("  NAMESPACE: '").append(namespace).append("',\n");

      // Attributes (only on CapabilityDefinition)
      if (def instanceof CapabilityDefinition) {
         CapabilityDefinition cap = (CapabilityDefinition) def;

         // ATTR_ constants
         for (AttributeDefinition attr : cap.getAttributes()) {
            sb.append("  ATTR_").append(attr.getName().toUpperCase())
              .append(": '").append(namespace).append(":").append(attr.getName()).append("',\n");
         }

         // Enum value constants
         for (AttributeDefinition attr : cap.getAttributes()) {
            for (String val : attr.getEnumValues()) {
               sb.append("  ").append(attr.getName().toUpperCase()).append("_").append(val.toUpperCase())
                 .append(": '").append(val).append("',\n");
            }
         }
      }

      // CMD_ constants
      for (MethodDefinition method : def.getMethods()) {
         sb.append("  CMD_").append(method.getName().toUpperCase())
           .append(": '").append(namespace).append(":").append(method.getName()).append("',\n");
      }

      // EVENT_ constants
      for (EventDefinition event : def.getEvents()) {
         sb.append("  EVENT_").append(event.getName().toUpperCase())
           .append(": '").append(namespace).append(":").append(event.getName()).append("',\n");
      }

      sb.append("} as const;\n");
   }

   private void writeFile(String fileName, String contents) throws IOException {
      File outputFile = new File(outputDirectory, fileName);
      if (outputFile.getParentFile() != null) {
         outputFile.getParentFile().mkdirs();
      }
      try (Writer writer = new FileWriter(outputFile)) {
         writer.write(contents);
      }
   }
}
