/*
 * Copyright 2019 Arcus Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
apply from: file("${rootDir}/gradle/subproject.gradle")

dependencies {
   api project(':agent:arcus-hal:arcus-hal-api')
   
   api project(':common:arcus-client')
   api project(':common:arcus-protocol')
   api project(':common:arcus-common')
   api project(':common:arcus-model')
   api project(':common:arcus-model:platform-messages')
   api project(':common:arcus-drivers:drivers-common')

   api libraries.guiceCore
   api 'commons-lang:commons-lang:2.6'
   api libraries.commonsIO
   api libraries.commonsCodec
   api libraries.sqlite4java
   api libraries.httpCore
   api libraries.httpClient
   api libraries.httpMime
   api libraries.guava
   api libraries.logback
   testImplementation libraries.junit
   implementation libraries.kxml2
   api libraries.bouncycastle
   api libraries.bouncycastle_pki

   api netty_handler
   api netty_codec_http
   api netty_codec
   api netty_transport
   api netty_buffer
   api netty_common
   api netty_tcnative
   api netty_epoll
   implementation name: 'netty-transport-native-epoll-4.0.41.Final-linux-armpoky21'

   api libraries.rxjava
   api libraries.rxjava_async

   api libraries.jetty_servlet
   api libraries.asyncHTTPClient
}

