/*
 * Copyright 2019 Arcus Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// project specific build settings, dependencies, etc.
apply from: file("${rootDir}/gradle/subproject.gradle")
apply from: file("${rootDir}/gradle/jaxb.gradle")

dependencies {
   api project (':platform:arcus-info')
   // TODO should really be a runtime dependency
   api project (':platform:arcus-log')
   api project (':platform:arcus-security')
   api project (':platform:arcus-prodcat')
   api project (':platform:arcus-rules')
   api project (':common:arcus-client')
   api project (':common:arcus-common')
   api project (':common:arcus-metrics')
   api project (':common:arcus-drivers:drivers-common')
   api project(':common:arcus-model:platform-messages')
   api project(':common:arcus-protocol')

   implementation dependencies.create(libraries.easymock) { transitive false }

   // anything that depends on arcus-lib should be capable of
   // handling jvm metrics
   api libraries.metrics_jvm

   api libraries.prometheus_dropwizard
   api libraries.prometheus_servlet
   api libraries.jetty_servlet

   api libraries.zookeeper
   api libraries.kafka
   api libraries.cassandraDriver
   api libraries.guiceCore
   api libraries.guiceServlet
   api libraries.guiceMultibindings
   api libraries.governator
   api libraries.shiro
   api libraries.metrics_core
   api libraries.metrics_json
   api libraries.handlebars
   implementation libraries.opencsv
   api libraries.joda

   implementation libraries.jcommander

   // TODO need a custom scope for this, providedCompile is part of war plugin
   api libraries.javaxServlet

   implementation libraries.azure_storage
   implementation libraries.commons_beanutils
   api libraries.bouncycastle
   implementation libraries.slf4jJul

   runtimeOnly libraries.jacksonCore
   runtimeOnly libraries.jacksonDatabind
   runtimeOnly libraries.commonsConfig
   runtimeOnly libraries.jaxb_impl
   runtimeOnly libraries.javax_activation_api
   runtimeOnly libraries.javax_activation_impl
   
   testImplementation project (':platform:arcus-test')
}

test {
   minHeapSize '512m'
   maxHeapSize '512m'
}

clean {
    delete "target"
}

jaxb {
   schemaDirIncludes = "scene/scene-catalog.xsd"
   packageName = 'com.iris.platform.scene.catalog.serializer'
}

